gender = ["M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "M","M","M","M","M","M","M","M","M","M",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W",
          "W","W","W","W","W","W","W","W","W","W"
          ]

age =  ["Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Child","Child","Child","Child","Child","Child","Child","Child","Child","Child",

        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult","Adult",
        "Child","Child","Child","Child","Child","Child","Child","Child","Child","Child"
        ]

outfit = ["Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant",
          "Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant",
          "Casual","Casual","Casual","Casual","Casual","Elegant","Elegant","Elegant","Elegant","Elegant",

          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual","Casual",
          "Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant",
          "Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant","Elegant",
          "Casual","Casual","Casual","Casual","Casual","Elegant","Elegant","Elegant","Elegant","Elegant"
          ]

cash = ["+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "-","-","-","-","-","-","-","-","-","-",
        "-","-","-","-","-","-","-","-","-","-",
        "-","-","-","-","-","-","-","-","-","-",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "-","+","-","+","-","+","-","+","-","+",

        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "-","-","-","-","-","-","-","-","-","-",
        "-","-","-","-","-","-","-","-","-","-",
        "-","-","-","-","-","-","-","-","-","-",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "+","+","+","+","+","+","+","+","+","+",
        "-","+","-","+","-","+","-","+","-","+"
        ]


time = ["Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Evening","Evening","Afternoon","Afternoon","Evening","Evening","Afternoon","Afternoon",

        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon","Afternoon",
        "Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening","Evening",
        "Afternoon","Afternoon","Evening","Evening","Afternoon","Afternoon","Evening","Evening","Afternoon","Afternoon"
        ]

vege = ["No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","Yes","Yes",

        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","No","No",
        "No","No","No","No","No","Yes","Yes","Yes","Yes","Yes",
        "No","No","No","No","No","No","No","No","Yes","Yes"
        ]

food = ['club_sandwich','steak','hot_dog','hamburger','hot_dog',
        'hot_dog','hot_dog','club_sandwich','steak','club_sandwich',
        'hamburger','steak','hamburger','club_sandwich','hot_dog',
        'hot_dog','steak','hot_dog','apple_pie','ice_cream',
        'pizza','hot_dog','hamburger','steak','club_sandwich',

        'ice_cream','waffles','greek_salad','greek_salad','greek_salad',
        'lasagna','lasagna','ice_cream','ice_cream','steak',
        'greek_salad','waffles','greek_salad','apple_pie','waffles',
        'hamburger','pizza','lasagna','hamburger','hamburger',
        'ice_cream','waffles','greek_salad','club_sandwich','ice_cream',

        'pizza','ice_cream','pizza','greek_salad','ice_cream',
        'lasagna','pizza','pizza','hamburger','club_sandwich',
        'club_sandwich','pizza','club_sandwich','apple_pie','club_sandwich',
        'ice_cream','waffles','greek_salad','apple_pie','greek_salad',
        'club_sandwich','steak','pizza','hamburger','hot_dog',

        'hamburger','steak','hot_dog','steak','hot_dog',
        'hot_dog','hot_dog','hamburger','steak','club_sandwich',
        'greek_salad','waffles','waffles','apple_pie','greek_salad',
        'club_sandwich','club_sandwich','pizza','waffles','apple_pie',
        'hot_dog','ice_cream','greek_salad','apple_pie','ice_cream',

        'club_sandwich','steak','steak','hamburger','hot_dog',
        'hot_dog','hot_dog','club_sandwich','steak','club_sandwich',
        'hamburger','steak','steak','lasagna','hot_dog',
        'hot_dog','ice_cream','greek_salad','pizza','ice_cream',
        'hot_dog','hot_dog','hamburger','steak','club_sandwich',

        'waffles','waffles','greek_salad','waffles','greek_salad',
        'lasagna','lasagna','lasagna','lasagna','lasagna',
        'ice_cream','waffles','waffles','apple_pie','greek_salad',
        'pizza','pizza','hamburger','hamburger','ice_cream',
        'ice_cream','waffles','greek_salad','apple_pie','ice_cream',

        'lasagna','ice_cream','hamburger','hamburger','ice_cream',
        'hamburger','hamburger','pizza','pizza','ice_cream',
        'lasagna','hot_dog','hamburger','steak','club_sandwich',
        'ice_cream','waffles','greek_salad','apple_pie','ice_cream',
        'club_sandwich','steak','hot_dog','hamburger','hot_dog',

        'hamburger','steak','hot_dog','hamburger','hot_dog',
        'hot_dog','steak','hamburger','steak','club_sandwich',
        'ice_cream','waffles','greek_salad','apple_pie','greek_salad',
        'ice_cream','ice_cream','lasagna','apple_pie','apple_pie',
        'hot_dog','ice_cream','hot_dog','apple_pie','waffles'
        ]

drink = ["Whisky","Whisky","Whisky","Whisky","Whisky",
         "Whisky","Whisky","Beer","Beer","Beer",
         "Cola","Water","Orange Juice","Water","Beer",
         "Cola","Water","Orange Juice","Cola","Beer",
         "Beer","Beer","Beer","Beer","Beer",

         "Beer","Beer","Beer","Beer","Beer",
         "Cola","Water","Orange Juice","Water","Beer",
         "Cola","Water","Orange Juice","Cola","Beer",
         "Beer","Beer","Beer","Beer","Beer",
         "Beer","Beer","Beer","Beer","Beer",

         "Cola","Water","Orange Juice","Water","Beer",
         "Cola","Water","Orange Juice","Cola","Beer",
         "Whisky","Whisky","Whisky","Whisky","Whisky",
         "Whisky","Whisky","Whisky","Beer","Beer",
         "Beer","Beer","Beer","Beer","Beer",

         "Cola","Water","Orange Juice","Water","Beer",
         "Beer","Beer","Beer","Beer","Beer",
         "Beer","Beer","Beer","Beer","Beer",
         "Orange Juice","Orange Juice","Cola","Cola","Cola",
         "Cola","Cola","Cola","Cola","Cola",

         "Whisky","Whisky","Whisky","Red Wine","Red Wine",
         "Red Wine","Red Wine","Red Wine","Red Wine","Whisky",
         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",

         "Whisky","Whisky","Whisky","Red Wine","Red Wine",
         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",

         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",
         "Red Wine","Red Wine","Whisky","Whisky","Whisky",
         "Water","Water","Orange Juice","Orange Juice","Cola",

         "Water","Water","Orange Juice","Orange Juice","Cola",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",
         "Red Wine","Red Wine","Red Wine","Red Wine","Red Wine",
         "Orange Juice","Orange Juice","Orange Juice","Orange Juice","Orange Juice",
         "Orange Juice","Orange Juice","Orange Juice","Cola","Cola"
         ]
